### ISSUE TITLE
recFile does not take absolute paths

### ISSUE THREAD

**Issue by ben-bay** [XiaohuaZhangLLNL/conveyorlc#2]
https://github.com/XiaohuaZhangLLNL/conveyorlc/blob/109290b6087830f3378f8b176bfb4af6e568a13a/apps/conduitppl/mpiparser.cpp#L331

My input is:
```
CDT3Docking ... --recFile <absolute path>
```
...but the program breaks the path by prepending `./` to it. Merlin and Maestro will need absolute path support for this to work.

**Comment by XiaohuaZhangLLNL** [comment]
Fixed. Program will check for the absolute path
