### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by vsoch** [XiaohuaZhangLLNL/conveyorlc#5]
Hiya! I'm trying to make this into a nix package, and ideally I could do that from a release! I noticed there hasn't been a release since 2018 - would it be possible to draft one soonish? :thinking:

**Comment by vsoch** [comment]
If not no worries - I can build from the current main branch commit.

**Comment by XiaohuaZhangLLNL** [comment]
Hi Vanessa,

I have added you to the conveyorlc GitHub repo.
Let me know if you still have trouble to update the code.

Thank you!

Xiaohua Zhang

From: Vanessasaurus ***@***.***>
Date: Monday, November 28, 2022 at 5:04 PM
To: XiaohuaZhangLLNL/conveyorlc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [XiaohuaZhangLLNL/conveyorlc] New Release? (Issue #5)

If not no worries - I can build from the current main branch commit.

**Comment by vsoch** [comment]
Thank you! The git commit should work I think. I might have another question about the find conduit Cmake file - will open another issue.
